#!/bin/bash

pkgs=(
      "i3-gaps" 
      "i3blocks" 
      "i3lock" 
      "i3status" 
      "lightdm" 
      "lightdm-gtk-greeter"
      "dmenu" 
      "ranger" 
      "kitty" 
      "ttf-hack" 
      "vim" 
      "tmux" 
      "htop" 
      "zsh"
)

failedPkgs=()

for p in ${pkgs[@]}
do
	sudo pacman --noconfirm -S $p || failedPkgs+=($p)
done

printf "\n%-20s %-10s\n" "PACKAGE" "STATUS"
printf "%-20s %-10s\n"   "=======" "========="

for p in ${pkgs[@]}
do
	
	if [[ "${failedPkgs[@]}" =~ "$p" ]]; then
		printf "%-20s [\e[1;31m%-7s\e[0m]\n" "$p" "failure"
	else
		printf "%-20s [\e[1;32m%-7s\e[0m]\n" "$p" "success"
	fi
done

#exec sudo systemctl enable lightdm
